### ISSUE TITLE
Notebook

### ISSUE THREAD

**Issue by acodignotto** [Vitor-Felix/notebooks#1]
# NOTEBOOK
### notebook

**Comment by GabrielTrev95** [comment]
---
# 📓
---

**Comment by ebrunaldi** [comment]
![image](https://github.com/Vitor-Felix/notebooks/assets/83730469/6a91277c-8e25-430d-9c7c-cc2dd76f8d71)

**Comment by Vitor-Felix** [comment]
#2 
![DALL·E 2023-10-28 13 39 11 - A photo of a person dressed as book mascot, painting a notebook computer, on a paper](https://github.com/Vitor-Felix/notebooks/assets/10060108/879557dd-b220-4f2a-ba62-304137e703da)
